// <auto-generated />
using System;
using LiftBattery.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LiftBattery.Api.Data.Migrations
{
    [DbContext(typeof(LiftBatteryDbContext))]
    [Migration("20260621091636_InitialPreCheckPersistence")]
    partial class InitialPreCheckPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LiftBattery.Api.Data.Entities.PreCheckEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<int>("Motivation")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PreCheckDate")
                        .HasColumnType("date");

                    b.Property<int>("PreviousSessionDurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("PreviousSessionRpe")
                        .HasColumnType("int");

                    b.Property<int>("RestingHeartRateDelta")
                        .HasColumnType("int");

                    b.Property<decimal>("SleepHours")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<int>("Soreness")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "PreCheckDate")
                        .IsUnique()
                        .HasDatabaseName("UX_PreChecks_UserId_PreCheckDate");

                    b.ToTable("PreChecks", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
